apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gs-rest-service-deployment
  namespace: hello-cloud-native
  labels:
    app: gs-rest-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gs-rest-service
  template:
    metadata:
      labels:
        app: gs-rest-service
    spec:
      containers:
      - name: gs-rest-service
        image: containers.cisco.com/codeplayground/gs-rest-service:1
        ports:
        - containerPort: 8080      
        resources:
          limits:
            memory: 1Gi
